version: "2"

services:
  web:
    build: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    networks:
      - lucid-net
    depends_on:
      - ollama

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - lucid-volume:/root/.ollama
    networks:
      - lucid-net
    restart: "no"  # Prevent automatic restarts
    healthcheck:  # Health check to ensure Ollama service is running
      test: ["CMD", "curl", "-f", "http://127.0.0.1:11434"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  lucid-net:
    driver: bridge

volumes:
  lucid-volume:
    driver: local